Neos:
  Neos:
    Ui:
      frontendConfiguration:
        'Carbon.Editor.Styling.TextInput':
          # allowEmpty false is only working for type number
          allowEmpty: true
          allowFloat: false
          debounce: 500
          disabled: false
          max: null
          min: null
          placeholder: ''
          setFocus: false
          title: null
          type: 'text'
          unit: null
          # If type = password, allowMakePasswordVisible we can switch the input type
          allowMakePasswordVisible: true
        'Carbon.Editor.Styling.TextAreaWithCounter':
          disabled: false
          maxlength: null
          readonly: false
          placeholder: ''
          minRows: 2
          maxRows: 24
          expandedRows: 6
          # If set to true, the counter is shown
          showCounter: true
          # If set to true, the counter count also the placeholder
          countPlaceholder: false
          # If set to true, it is allowed to add line breaks
          allowLineBreaks: true
          # Number. If smaller than the current length, the text is marked as warning
          warningLengthMin: null
          # Number. If smaller than the current length, the text is marked as error
          errorLengthMin: null
          # Number. If greater than the current length, the text is marked as warning
          warningLengthMax: null
          # Number. If greater than the current length, the text is marked as error
          errorLengthMax: null
        'Carbon.Editor.Styling.Border':
          placeholder: ''
          disabled: false
          readonly: false
          allowEmpty: true

          # Convert px values to rem when saving to content repository
          convertPxToRem: false

          allowWidth: true
          allowStyle: true
          allowColor: true
          allowColorPicker: true
          allowColorInput: true
          allowCurrentColor: true
          allowTransparent: false
          defaultColor: 'currentColor'
          borderStyles:
            solid: true
            dashed: true
            dotted: true
            double: true
            groove: false
            ridge: false
            inset: false
            outset: false
          presetColors: []
          minBorderWidth: 0
          maxBorderWidth: 100
        'Carbon.Editor.Styling.BorderRadius':
          placeholder: ''
          disabled: false
          readonly: false
          allowEmpty: false

          # Allow mutliple values
          allowMultiple: false

          # Allow organic shapes
          # If true dialog will be shown to set multiple values and it is possible to create organic shapes
          allowOrganic: false

          # Allow full rounded value
          allowFullRounded: false

          # Allow percentage values
          allowPercentage: false

          # Convert px values to rem when saving to content repository
          convertPxToRem: true

          # true or false
          preview: true
          # Has only a affect on big preview (after the user has clicked on the small preview)
          previewAspectRatio: null

          # min, max and fullRoundedValue are always in px, even if convertPxToRem is true
          # The full rounded value will be saved with the pixel unit in the database
          # The other values will be converted and saved with the rem unit in the database if convertPxToRem is true
          # If in percentage mode, min and max have no effect, there is always the range between 0 and 100
          min: 0
          max: 24
          fullRoundedValue: 9999
        'Carbon.Editor.Styling.Spacing':
          placeholder: ''
          disabled: false
          readonly: false
          allowEmpty: false

          # Allow mutliple values
          # If you want to restrict to certain directions, you can set a string with multiple values separated by a space
          # Example: 'top right'
          allowMultiple: false

          # Allow to sync values (x and y axis)
          allowSync: true

          # Convert px values to rem when saving to content repository
          convertPxToRem: false

          # min, max and fullRoundedValue are always in px, even if convertPxToRem is true
          # The values will be converted and saved with the rem unit in the database if convertPxToRem is true
          min: 0
          max: 999
        'Carbon.Editor.Styling.BackgroundSize':
          disabled: false
          readonly: false
          placeholder: ''
          min: 1
          max: null
          allowPixel: true
          allowPercentage: true
          allowContain: true
          allowAuto: true
          allowCover: true
