Neos:
  Neos:
    Ui:
      frontendConfiguration:
        'Carbon.Editor.Styling.TextAreaWithCounter':
          disabled: false
          maxlength: null
          readonly: false
          placeholder: ''
          minRows: 2
          maxRows: 24
          expandedRows: 6
          showCounter: true
          countPlaceholder: false
          allowLineBreaks: true
          warningLengthMin: null
          errorLengthMin: null
          warningLengthMax: null
          errorLengthMax: null
        'Carbon.Editor.Styling.BorderRadius':
          placeholder: ''
          disabled: false
          readonly: false
          allowMultiple: true
          allowFullRounded: false
          convertToRem: true

          # false, big, or small
          preview: false
          # Has only a affect on big preview
          previewAspectRatio: null

          # min, max and fullRoundedValue are always in px
          min: 0
          max: 24
          fullRoundedValue: 9999
